# Use latest dwi67/jboss-fuse-6.3 image as the base
FROM hammj/jboss-fuse-6.3

MAINTAINER Joshua Hamm <hammj@sutterhealth.org>

# Copy the users properties to enable the console
COPY users.properties /opt/jboss/jboss-fuse/etc/
